// Generated by gencpp from file task3_pkg/node1.msg
// DO NOT EDIT!


#ifndef TASK3_PKG_MESSAGE_NODE1_H
#define TASK3_PKG_MESSAGE_NODE1_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task3_pkg
{
template <class ContainerAllocator>
struct node1_
{
  typedef node1_<ContainerAllocator> Type;

  node1_()
    : data1()
    , data2(0)  {
    }
  node1_(const ContainerAllocator& _alloc)
    : data1(_alloc)
    , data2(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _data1_type;
  _data1_type data1;

   typedef int32_t _data2_type;
  _data2_type data2;





  typedef boost::shared_ptr< ::task3_pkg::node1_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task3_pkg::node1_<ContainerAllocator> const> ConstPtr;

}; // struct node1_

typedef ::task3_pkg::node1_<std::allocator<void> > node1;

typedef boost::shared_ptr< ::task3_pkg::node1 > node1Ptr;
typedef boost::shared_ptr< ::task3_pkg::node1 const> node1ConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task3_pkg::node1_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task3_pkg::node1_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::task3_pkg::node1_<ContainerAllocator1> & lhs, const ::task3_pkg::node1_<ContainerAllocator2> & rhs)
{
  return lhs.data1 == rhs.data1 &&
    lhs.data2 == rhs.data2;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::task3_pkg::node1_<ContainerAllocator1> & lhs, const ::task3_pkg::node1_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace task3_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::task3_pkg::node1_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task3_pkg::node1_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3_pkg::node1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task3_pkg::node1_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3_pkg::node1_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task3_pkg::node1_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task3_pkg::node1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ca2ba9eef5388fbdc1aa511d4795378a";
  }

  static const char* value(const ::task3_pkg::node1_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xca2ba9eef5388fbdULL;
  static const uint64_t static_value2 = 0xc1aa511d4795378aULL;
};

template<class ContainerAllocator>
struct DataType< ::task3_pkg::node1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task3_pkg/node1";
  }

  static const char* value(const ::task3_pkg::node1_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task3_pkg::node1_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data1\n"
"int32 data2\n"
;
  }

  static const char* value(const ::task3_pkg::node1_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task3_pkg::node1_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data1);
      stream.next(m.data2);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct node1_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task3_pkg::node1_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task3_pkg::node1_<ContainerAllocator>& v)
  {
    s << indent << "data1: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.data1);
    s << indent << "data2: ";
    Printer<int32_t>::stream(s, indent + "  ", v.data2);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK3_PKG_MESSAGE_NODE1_H
